/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package controlEstacionamiento;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author LENOVO
 */
public class Grafica extends javax.swing.JFrame {

    /**
     * Creates new form Grfica
     */
    public Grafica() {
        initComponents();

        this.setLocationRelativeTo(null);
        getContentPane().setBackground(new Color(34,209,241));
        repaint();
    }
    
    

    private ListaEnlazada vehiculos;

    public void paint(Graphics g) {

        int total = vehiculos.cantidadAutos() + vehiculos.cantidadMotos();

        int grados_auto = vehiculos.cantidadAutos() * 360 / total;
        int grados_moto = vehiculos.cantidadMotos() * 360 / total;

        //graficar
        
        //para auto
        g.setColor(new Color(162, 204, 47));
        //dibuja un arco circular
        //        (x, y, ancho, largo, grado inicial, grado final)
        g.fillArc(25, 80, 200, 200, 0, grados_auto);
        //         (x, y, ancho, largo)
        g.fillRect(250, 120, 20, 20);
        //           (texto, x, y)
        g.drawString("Autos", 275, 135);
        
        //para moto
        g.setColor(new Color(217, 122, 79));
        //dibuja un arco circular
        //        (x, y, ancho, largo, grado inicial, grado final)
        g.fillArc(25, 80, 200, 200, grados_auto, grados_moto);
        //         (x, y, ancho, largo)
        g.fillRect(250, 130, 20, 20);
        //           (texto, x, y)
        g.drawString("Motos", 275, 165);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Vehiculos En Estacionamiento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel1)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(330, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
